name: My Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install
        run: echo "install"
        
      - name: Test
        run: echo "test"

      - name: Build
        run: echo "build package"
